[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# Set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# Copyright statement formatting
# copyright_header_text = Copyright (c) ...

sqlalchemy.url = postgresql+asyncpg://kitchan_user:kitchan_password@localhost:5432/kitchan_db


[post_write_hooks]
# text which specifies a post-write hook, like black, ruff, etc.
# hooks = black
# black.options = --line-length 79

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_level]
# Set the log level here (DEBUG, INFO, WARNING, ERROR, CRITICAL)
# Note: alembic.runtime.migration will output SQL statements at DEBUG level

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_class]

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(asctime)s] %(levelname)s %(name)s: %(message)s
datefmt = %H:%M:%S