"""feat: crear tabla restaurantes y fk en usuarios

Revision ID: 6d964f82bbbd
Revises: 1ce17829104b
Create Date: 2026-07-23 18:36:53.659966

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d964f82bbbd"
down_revision: Union[str, None] = "1ce17829104b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurantes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre_comercial", sa.String(length=150), nullable=False),
        sa.Column("razon_social", sa.String(length=150), nullable=False),
        sa.Column("identificacion_fiscal", sa.String(length=20), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=False),
        sa.Column("email_corporativo", sa.String(length=255), nullable=False),
        sa.Column("estado", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identificacion_fiscal"),
    )
    op.create_index(op.f("ix_restaurantes_id"), "restaurantes", ["id"], unique=False)
    op.add_column("usuarios", sa.Column("restaurante_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "usuarios", "restaurantes", ["restaurante_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.drop_column("usuarios", "restaurante_id")
    op.drop_index(op.f("ix_restaurantes_id"), table_name="restaurantes")
    op.drop_table("restaurantes")
    # ### end Alembic commands ###
